# Provider network parameters
export PROVIDER_PHYSICAL_NETWORK=public
export PROVIDER_NET_NAME=external
export PROVIDER_SUBNET_NAME=sub_ext
export PROVIDER_NETWORK_CIDR=192.168.2.0/24
export PROVIDER_SUBNET_START_IP_ADDRESS=192.168.2.60
export PROVIDER_SUBNET_END_IP_ADDRESS=192.168.2.89
export PROVIDER_NETWORK_GATEWAY=192.168.2.1
export PROVIDER_DNS_RESOLVER=8.8.4.4

# Selfservice network parameters
export SELF_SERVICE_NET_NAME=internal
export SELF_SERVICE_SUBNET_NAME=sub_int
export SELFSERVICE_NETWORK_CIDR=172.17.0.0/24
export SELFSERVICE_NETWORK_GATEWAY=172.17.0.1
export SELFSERVICE_DNS_RESOLVER=8.8.4.4

# Router parameters
export TENANT_ROUTER_NAME=r_admin
